routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');


//login
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//showPages
Route::get('/page/{slug}', 'HomeController@showPage');

//contactMessage to User
Route::post('/sendMessage', 'HomeController@sendMessage');

//playgruond
Route::resource('/playgrounds', 'PlaygroundController');

//courts
Route::resource('/courts', 'CourtController');

//events
Route::resource('/events', 'SportEventController');
//Route::post('/joinLeaveEvent', 'SportEventController@joinLeaveEvent');
Route::post('/event/{id}', 'SportEventController@joinLeaveEvent')->name('join.event');

//admin/profile/change-password
Route::get('/profile', 'ProfileController@showProfile');
Route::put('/profile', 'ProfileController@updateProfile')->name('update.profile');


Route::get('/password', 'ProfileController@changePassword');
Route::post('/password', 'ProfileController@updatePassword')->name('change.password');

app/Models/EventType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class EventType extends Model
{
    protected $table = 'event_types';

    protected $fillable = ['name'];

    protected $hidden = [];

    public function sport_events() {
        return $this->hasMany(SportEvent::class, 'event_types_id');
    }
}

resources/views/events/create.blade.php
@extends('layouts.page') @section('caption', 'Create events') @section('content')

<nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link " href="/dashboard">
                        <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="javascript:void(0)" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-list-ul" aria-hidden="true"></i> Listing
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/">My Listing</a>
                        <a class="dropdown-item" href="/">Add Listing</a>
                        <a class="dropdown-item" href="/">Edit Listing</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="/">
                        <i class="fa fa-envelope" aria-hidden="true"></i> Messages <span class="badge badge-success">12</span> </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="/">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Booking Request </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="/">
                        <i class="fa fa-eye" aria-hidden="true"></i> Reviews </a>
                </li>

            </ul>

            <form class="form-inline my-2 my-lg-0 position-relative d-none d-md-block">
                <input class="form-control-sm" placeholder="Search" aria-label="Search">
                <i class="fa fa-search" aria-hidden="true"></i>
            </form>
        </div>
    </div>
</nav>

<!-- ====================================
———	Add Listing
===================================== -->
<section class="bg-light py-5 height100vh">
    <div class="container">
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h2 class="font-weight-normal mb-4 mb-md-0">Submit Listings</h2>
            <ul class="list-unstyled d-flex p-0 m-0">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="dashboard-list-admin.html">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Submit Listings</li>
            </ul>
        </nav>

        <form action="{{ route('events.store') }}" method="POST">
            @csrf

            <!-- About -->
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    <h3 class="h4 mb-4">About</h3>
                    <p class="mb-5">We are not responsible for any damages caused by the use of this website, or by posting business listings here. Please use our site at your own discretion and exercise good judgement as well as common sense when advertising business here.</p>
                    <div class="row">
                        <div class="form-group col-md-6 mb-6">
                            <label for="eventName">Event Name</label>
                            <input type="text" class="form-control" id="eventName" name="name" placeholder="Event Name" required>
                        </div>

                        <div class="form-group col-md-3 mb-6">
                            <label for="startsAt">Starting time</label>
                            <input type="text" class="form-control" id="startsAt" name="starts_at" placeholder="Starts At" required>
                        </div>

                        <div class="form-group col-md-3 mb-6">
                            <label for="endsAt">Ending time</label>
                            <input type="text" class="form-control" id="endsAt" name="ends_at" placeholder="Ends At">
                        </div>

                        <div class="form-group col-md-12 mb-6">
                            <label for="description">Description</label>
                            <textarea class="form-control" rows="6" id="description" name="description" placeholder="Describe the event" required></textarea>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="no_of_players">Numbers of players</label>
                            <input type="text" class="form-control" id="no_of_players" name="no_of_players" placeholder="Number of players" required>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="openSlots">Open Slots</label>
                            <input type="text" class="form-control" id="openSlots" name="open_slots" placeholder="Open Slots" required>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="price">Price</label>
                            <input type="text" class="form-control" id="price" name="price" placeholder="Price" required>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="event_statuses_id">Event Status</label>
                            <div class="select-default bg-white">
                                <select class="select-location" name="event_statuses_id" required>

                                        @foreach($event_statuses as $event_status)
                                    <option value="{{ $event_status->id }}">{{ $event_status->name }}</option>
                                        @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="sport_types_id">Sport Type</label>
                            <div class="select-default bg-white">
                                <select class="select-location" name="sport_types_id" required>
                            
                                        @foreach($sport_types as $sport_type)
                                    <option value="{{ $sport_type->id }}">{{ $sport_type->name }}</option>
                                        @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="exampleFormControlSelect1">Event Type</label>
                            <div class="select-default bg-white">
                                <select class="select-location" name="event_types_id" required>

                                        @foreach($event_types as $event_type)
                                    <option value="{{ $event_type->id }}">{{ $event_type->name }}</option>
                                        @endforeach
                                </select>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-md-7 col-lg-6 col-xl-5">
                        <div class="mb-6">
                            <button type="submit" id="contact-submit" class="btn btn-lg btn-primary btn-block">submit</button>
                        </div>
                    </div>
                </div>

                    @if ($errors->any())
                <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
                </div>
                    @endif

            </div>
        </form>
    </div>
</section>

</div>
<!-- element wrapper ends -->
@endsection

@section('footerJS')
   <script>
       $(document).ready(function () {
            $('#startsAt').daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                timePicker: true,
                timePicker24Hour: true,
                timePickerIncrement: 15,
                minYear: 2000,
                locale: {
                    format: 'YYYY-MM-DD hh:mm'
                }
            });
        });
        
        $(document).ready(function () {
            $('#endsAt').daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                timePicker: true,
                timePicker24Hour: true,
                timePickerIncrement: 15,
                minYear: 2000,
                locale: {
                    format: 'YYYY-MM-DD hh:mm'
                }
            });
        });
    </script>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.page')

@section('caption', 'Edit events')

@section('content')

<nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link " href="/dashboard">
                        <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="javascript:void(0)" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-list-ul" aria-hidden="true"></i> Listing
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/">My Listing</a>
                        <a class="dropdown-item" href="/">Add Listing</a>
                        <a class="dropdown-item" href="/">Edit Listing</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="/">
                        <i class="fa fa-envelope" aria-hidden="true"></i> Messages <span class="badge badge-success">12</span> </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="/">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Booking Request </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="/">
                        <i class="fa fa-eye" aria-hidden="true"></i> Reviews </a>
                </li>

            </ul>

            <form class="form-inline my-2 my-lg-0 position-relative d-none d-md-block">
                <input class="form-control-sm" placeholder="Search" aria-label="Search">
                <i class="fa fa-search" aria-hidden="true"></i>
            </form>
        </div>
    </div>
</nav>

<!-- ====================================
———	Add Listing
===================================== -->
<section class="bg-light py-5 height100vh">
    <div class="container">
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h2 class="font-weight-normal mb-4 mb-md-0">Submit Listings</h2>
            <ul class="list-unstyled d-flex p-0 m-0">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="dashboard-list-admin.html">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Submit Listings</li>
            </ul>
        </nav>

        <form action="/events/{{ $event->id }}" method="POST">
            @method('PUT')
            @csrf

            <!-- About -->
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    <h3 class="h4 mb-4">About</h3>
                    <p class="mb-5">We are not responsible for any damages caused by the use of this website, or by posting business listings here. Please use our site at your own discretion and exercise good judgement as well as common sense when advertising business here.</p>
                    <div class="row">
                        <div class="form-group col-md-6 mb-6">
                            <label for="eventName">Event Name</label>
                            <input type="text" class="form-control" id="eventName" name="name" placeholder="Event Name" value="{{ $event->name }}" required>
                        </div>

                        <div class="form-group col-md-3 mb-6">
                            <label for="startsAt">Starting time</label>
                            <input type="text" class="form-control" id="startsAt" name="starts_at" placeholder="Starts At" value="{{ $event->starts_at }}" required>
                        </div>

                        <div class="form-group col-md-3 mb-6">
                            <label for="endsAt">Ending time</label>
                            <input type="text" class="form-control" id="endsAt" name="ends_at" placeholder="Ends At" value="{{ $event->ends_at }}">
                        </div>

                        <div class="form-group col-md-12 mb-6">
                            <label for="description">Description</label>
                            <textarea class="form-control" rows="6" id="description" name="description" placeholder="Describe the event" required>{{ $event->description }}</textarea>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="no_of_players">Numbers of players</label>
                            <input type="number" min="1" max="11" class="form-control" id="no_of_players" name="no_of_players" placeholder="Number of players" value="{{ $event->no_of_players }}" required>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="openSlots">Open Slots</label>
                            <input type="number" min="1" max="1" class="form-control" id="openSlots" name="open_slots" placeholder="Open Slots" value="{{ $event->open_slots }}" required>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="price">Price</label>
                            <input type="number" min="1" class="form-control" id="price" name="price" placeholder="Price" value="{{ $event->price }}" required>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="event_statuses_id">Event Status</label>
                            <div class="select-default bg-white">
                                <select class="select-location" name="event_statuses_id" required>


                                    @foreach($event_statuses as $event_status)
                                    <option value="{{ $event_status->id }}">{{ $event_status->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="sport_types_id">Sport Type</label>
                            <div class="select-default bg-white">
                                <select class="select-location" name="sport_types_id" required>


                                    @foreach($sport_types as $sport_type)
                                    <option value="{{ $sport_type->id }}">{{ $sport_type->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group col-md-4 mb-6">
                            <label for="exampleFormControlSelect1">Event Type</label>
                            <div class="select-default bg-white">
                                <select class="select-location" name="event_types_id" required>


                                    @foreach($event_types as $event_type)
                                    <option value="{{ $event_type->id }}">{{ $event_type->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-md-7 col-lg-6 col-xl-5">
                        <div class="mb-6">
                            <button type="submit" id="contact-submit" class="btn btn-lg btn-primary btn-block">submit</button>
                        </div>
                    </div>
                </div>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

            </div>
        </form>
    </div>
</section>

</div>
<!-- element wrapper ends -->
@endsection

@section('footerJS')
   <script>
       $(document).ready(function () {
            $('#startsAt').daterangepicker({
                singleDatePicker: true,
                timePicker24Hour: true,
                timePickerIncrement: 15,
                showDropdowns: true,
                timePicker: true,
                minYear: 2000,
                locale: {
                    format: 'YYYY-MM-DD hh:mm'
                }
            });
        });

        $(document).ready(function () {
            $('#endsAt').daterangepicker({
                singleDatePicker: true,
                timePicker24Hour: true,
                timePickerIncrement: 15,
                showDropdowns: true,
                timePicker: true,
                minYear: 2000,
                locale: {
                    format: 'YYYY-MM-DD hh:mm'
                }
            });
        });
    </script>
@endsection

resources/views/events/index.blade.php
@extends('layouts.page')

@section('caption', 'Events')

@section('content')

<!-- ====================================
———	LISTING HALF MAP LIST
===================================== -->
    <section class="main-contentiner map-half-content grid-two-items">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 order-lg-2 pl-lg-0">
                    <div class="inner-container">
                        <div class="map-lg-fixed">
                            <div class="map-container">
                                <div id="listing-main-map" class="map-half"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 px-xl-6">
                    <div class="row">
                        <div class="col-12">

                        @foreach($events as $event)
                            <!-- List items goes here -->
                                <div class="card card-list card-listing" data-lat="-33.922125" data-lag="151.159277" data-id="1">
                                    <div class="row">
                                        <div class="col-sm-5 col-xl-4">
                                            <div class="card-list-img">
                                                <img class="listing-img" src="/assets/img/listing/listing-4.jpg" alt="things-4">
                                                <a href="/">
                                                    <span class="badge badge-primary">{{ $event->users->name }}</span>
                                                </a>
                                            </div>
                                        </div>

                                        <div class="col-sm-7 col-xl-8">
                                            <div class="card-body p-0">

                                                <ul class="list-inline list-inline-rating">
                                                    <li class="list-inline-item">
                                                        <i class="fa fa-star" aria-hidden="true"></i>
                                                    </li>

                                                    <li class="list-inline-item text-primary">
                                                        {{ $event->starts_at }}
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <i class="fa fa-star" aria-hidden="true"></i>
                                                    </li>
                                                    <li class="list-inline-item text-primary">
                                                        {{ $event->ends_at }}
                                                    </li>
                                                </ul>

                                                <div class="d-flex justify-content-between align-items-center mb-1">
                                                    <h3 class="card-title listing-title mb-4">
                                                        <a href="/events/{{ $event->id }}">{{ $event->name }}</a>
                                                    </h3>

                                                    <button class="btn-like px-2" data-toggle="tooltip"
                                                            data-placement="top" title="Numbers of players">
                                                        <i class="text-primary"
                                                           aria-hidden="true">{{ $event->no_of_players }}</i>
                                                    </button>

                                                    <button class="btn-like px-2" data-toggle="tooltip"
                                                            data-placement="top" title="Open slots">
                                                        <span>{{ $event->open_slots }}</span>
                                                    </button>
                                                </div>
                                            </div>

                                            <p class="mb-4">{{ $event->description }}</p>

                                            <div>
                                                <i class="text-primary" aria-hidden="true" data-toggle="tooltip"
                                                   data-placement="top" title="Event status">
                                                    {{ $event->event_statuses->name }} / </i>
                                                <i class="text-primary" aria-hidden="true" data-toggle="tooltip"
                                                   data-placement="top" title="Sport Type">
                                                    {{ $event->sport_types->name }} / </i>
                                                <i class="text-primary" aria-hidden="true" data-toggle="tooltip"
                                                   data-placement="top" title="Event type">
                                                    {{ $event->event_types->name }} </i>
                                            </div>

                                            <ul class="list-inline list-inline-rating">
                                                <li class="list-inline-item">
                                                    <i class="fa fa-star" aria-hidden="true"></i>
                                                </li>
                                                <li class="list-inline-item text-primary">
                                                    {{ $event->created_at->format("d.M.Y. H:i") }}
                                                </li>
                                                <li class="list-inline-item">
                                                    <i class="fa fa-star" aria-hidden="true"></i>
                                                </li>
                                                <li class="list-inline-item text-primary">
                                                    {{ $event->updated_at }}
                                                </li>
                                            </ul>

                                            <form action="{{ route('join.event', $event->id) }}" method="POST">
                                                <!-- <input type="hidden" name="_method" value="PUT"> -->
                                                @csrf
                                                <!-- <a class="btn btn-primary pull-right px-6 py-2" href="#" role="button" id="buttonEvent {{ $event->id }}"
                                                    onclick="joinLeaveEvent( {{ $event->id }} );" return false>Join</a> -->
                                                    @if (!in_array($event->id, $userEvents))
                                                    <button class="btn btn-primary pull-right px-6 py-2 text-uppercase" id="buttonEvent{{ $event->id }}"
                                                        onclick="joinLeaveEvent( {{ $event->id }} ); return false;" type="submit" data-toggle="modal" data-target=".bd-example-modal-lg"> Join
                                                        </button>
                                                    @else
                                                    <button class="btn btn-danger pull-right px-6 py-2 text-uppercase" id="buttonEvent{{ $event->id }}"
                                                        onclick="joinLeaveEvent( {{ $event->id }} ); return false;"  type="submit" 
                                                        data-toggle="modal" data-target=".bd-example-modal-lg"> Leave
                                                        </button>
                                                    @endif
                                            </form>​
                                        </div>

                                    </div>
                                </div>
                            @endforeach

                            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm" role="document">
                                  <div class="modal-content">
                                    <div id="messageDiv"></div>
                                  </div>
                                </div>
                            </div>

                            <br/>

                            {{ $events->links() }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    </div> 
    <!-- element wrapper ends -->
@endsection

@section('footerJS')
    <script src="{{ url('') }}/js/helper.js"></script>
@endsection