routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');


//login
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//showPages
Route::get('/page/{slug}', 'HomeController@showPage');

//contactMessage to User
Route::post('/sendMessage', 'HomeController@sendMessage');

//playgruond
Route::resource('/playgrounds', 'PlaygroundController');

//courts
Route::resource('/courts', 'CourtController');

//events
Route::resource('/events', 'SportEventController');
//Route::post('/joinLeaveEvent', 'SportEventController@joinLeaveEvent');
Route::post('/event/{id}', 'SportEventController@joinLeaveEvent')->name('join.event');

//admin/profile/change-password
Route::get('/profile', 'ProfileController@showProfile');
Route::put('/profile', 'ProfileController@updateProfile')->name('update.profile');


Route::get('/password', 'ProfileController@changePassword');
Route::post('/password', 'ProfileController@updatePassword')->name('change.password');

app/Models/Court.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Playground;
use App\Models\CourtStatus;


class Court extends Model
{
    protected $table = 'courts';

    protected $fillable = ['playgrounds_id', 'name', 'description', 'court_statuses_id'];

    protected $hidden = [];

    public $timestamps = false;

    public function playgrounds() {
        return $this->belongsTo(Playground::class, 'playgrounds_id');
    } 
    
    public function court_statuses(){ 
        return $this->belongsTo(CourtStatus::class, 'court_statuses_id');
    }

    public function has_events() {
        return $this->belongsToMany(SportEvent::class, 'sport_events_has_court', 'courts_id', 'sport_events_id');
    }
}

app/Http/Controllers/CourtController.php
<?php

namespace App\Http\Controllers;

use App\Models\Court;
use App\Models\Playground;
use App\Models\CourtStatus;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class CourtController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct()
    {
         $this->middleware('auth', ['except'=>['index', 'show']]);
    }
    
    public function index()
    {   
        $courts = Court::with('playgrounds')
        ->with('court_statuses')
        ->paginate(15);

        return view('courts.index', compact('courts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $user = Auth::user();

        $playgrounds = ($user->user_types_id == 1) ? (Playground::all()):(Playground::where('users_id', $user->id)->get());
    
        $court_statuses = CourtStatus::all();

        return view('courts.create', compact('playgrounds', 'court_statuses', 'user'));
    }
        
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {  
        $validator = Validator::make($request->all(),[
            'playgrounds_id' => 'required|integer',
            'name' => 'required',
            'description' => 'required',
            'court_statuses_id' => 'required|integer'
        ])->validate();

        $playground = Playground::find($request->input('playgrounds_id'));

        $user = $request->user();
     
        if ($user->user_types_id == 1 || $playground->users_id == $user->id) {
        
            $data = $request->only(['playgrounds_id', 'name', 'description', 'court_statuses_id']);
            
            $court= Court::create($data); 

            return redirect('/courts/'.$court->id);
        }
        else {
            return abort(403);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $court = Court::findOrFail($id);

        return view('courts.view', compact('court'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();

        $court = Court::find($id);

        $playground = Playground::findOrFail($court->playgrounds_id);
    
        if ($user->user_types_id == 1 || $playground->users_id == $user->id) {

            //$playground = ($user->user_types_id == 1) ? Playground::all():Playground::where('users_id', $user->id)->get();
        
            $court_statuses = CourtStatus::all();
    
            return view('courts.edit', compact('court', 'playground', 'court_statuses', 'user'));
        }
        else {
            return abort(403);
        }
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'playgrounds_id' => 'required|integer',
            'name' => 'required',
            'description' => 'required',
            'court_statuses_id' => 'required|integer'
        ])->validate();

        $user = $request->user();

        $court = Court::findOrFail($id);

        $playground = Playground::findOrFail($court->playgrounds_id);

        if ($user->user_types_id == 1 || $playground->users_id == $user->id) {

            $court_statuses = CourtStatus::all();
    
            $data = $request->only(['playgrounds_id', 'name', 'description', 'court_statuses_id']);
        
            $court->update($data);
       
            return redirect('/courts/'.$court->id);
        }
        else {
            return abort(403);
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();

        $court = Court::find($id);
        
        $playground = Playground::find($court->playgrounds_id);

        if ($user->user_types_id == 1 || $playground->users_id == $user->id) {
            
            $court = Court::findOrFail($id)->delete();

            return redirect(route('courts.index'));
        } 
        else {
            return abort(403);
        }  
    }
}

resources/views/courts/create.blade.php
@extends('layouts.page')

@section('caption', 'Create Court')

@section('content')

      <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container">

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link " href="/dashboard">
                  <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="javascript:void(0)" id="navbarDropdown" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-list-ul" aria-hidden="true"></i> Listing
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/">My Listing</a>
                  <a class="dropdown-item" href="/">Add Listing</a>
                  <a class="dropdown-item" href="/">Edit Listing</a>
                </div>
              </li>

              <li class="nav-item">
                <a class="nav-link " href="/">
                  <i class="fa fa-envelope" aria-hidden="true"></i> Messages <span class="badge badge-success">12</span> </a>
              </li>

              <li class="nav-item">
                <a class="nav-link " href="/">
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Booking Request </a>
              </li>

              <li class="nav-item">
                <a class="nav-link " href="/">
                  <i class="fa fa-eye" aria-hidden="true"></i> Reviews </a>
              </li>

            </ul>

            <form class="form-inline my-2 my-lg-0 position-relative d-none d-md-block">
              <input class="form-control-sm" placeholder="Search" aria-label="Search">
              <i class="fa fa-search" aria-hidden="true"></i>
            </form>
          </div>
        </div>
      </nav>

<!-- ====================================
———	Add Listing
===================================== -->
<section class="bg-light py-5 height100vh">
  <div class="container">
    <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
	    <h2 class="font-weight-normal mb-4 mb-md-0">Submit Listings</h2>
	    <ul class="list-unstyled d-flex p-0 m-0">
				<li class="breadcrumb-item"><a href="/home">Home</a></li>
	      <li class="breadcrumb-item"><a href="/profile">Dashboard</a></li>
	      <li class="breadcrumb-item active" aria-current="page">Submit Listings</li>
	    </ul>
    </nav>

    <form action="{{ route('courts.store') }}" method="POST">
        @csrf   
            
      <!-- About -->
      <div class="card">
        <div class="card-body px-6 pt-6 pb-1">
          <h3 class="h4 mb-4">About</h3>
          <p class="mb-5">We are not responsible for any damages caused by the use of this website, or by posting business listings here. Please use our site at your own discretion and exercise good judgement as well as common sense when advertising business here.</p>
            <div class="row">
              <div class="form-group col-md-6 mb-6">
                <label for="courtName">Court Name </label>
                <input type="text" class="form-control" id="courtName" name="name" placeholder="Court Name" required>
              </div>

              <div class="form-group col-md-6 mb-6">
                <label for="playgrounds_id">Playground Name</label>
                <div class="select-default bg-white">
                  <select class="select-location" name="playgrounds_id" required>
                    
                        @foreach($playgrounds as $playground)
                    <option value="{{ $playground->id }}">{{ $playground->name }}</option>
                        @endforeach
                  </select>
                </div>
              </div>

              <div class="form-group col-md-12 mb-6">
                <label for="description">Description</label>
                <textarea class="form-control" rows="6" name="description" placeholder="Description" required></textarea>
              </div>

              <div class="form-group col-md-12 mb-6">
                <label for="court_statuses_id">Court Status</label>
                <div class="select-default bg-white">
                  <select class="select-location" name="court_statuses_id" required>

                        @foreach($court_statuses as $court_status)
                    <option value="{{ $court_status->id }}">{{ $court_status->name }}</option>
                        @endforeach
                  </select>
                </div>
              </div>

            </div>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-7 col-lg-6 col-xl-5">
          <div class="mb-6">
            <button type="submit" id="contact-submit" class="btn btn-lg btn-primary btn-block">submit</button>
          </div>
        </div>
      </div>
      
      @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
              @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
          </ul>
        </div>
      @endif

    </form>

  </div>
</section>

</div> <!-- element wrapper ends -->

@endsection

resources/views/courts/edit.blade.php
@extends('layouts.page')

@section('caption', 'Edit Court')

@section('content')

      <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container">

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link " href="/dashboard">
                  <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="javascript:void(0)" id="navbarDropdown" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-list-ul" aria-hidden="true"></i> Listing
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/">My Listing</a>
                  <a class="dropdown-item" href="/">Add Listing</a>
                  <a class="dropdown-item" href="/">Edit Listing</a>
                </div>
              </li>

              <li class="nav-item">
                <a class="nav-link " href="/">
                  <i class="fa fa-envelope" aria-hidden="true"></i> Messages <span class="badge badge-success">12</span> </a>
              </li>

              <li class="nav-item">
                <a class="nav-link " href="/">
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Booking Request </a>
              </li>

              <li class="nav-item">
                <a class="nav-link " href="/">
                  <i class="fa fa-eye" aria-hidden="true"></i> Reviews </a>
              </li>

            </ul>

            <form class="form-inline my-2 my-lg-0 position-relative d-none d-md-block">
              <input class="form-control-sm" placeholder="Search" aria-label="Search">
              <i class="fa fa-search" aria-hidden="true"></i>
            </form>
          </div>
        </div>
      </nav>

<!-- ====================================
———	Add Listing
===================================== -->
<section class="bg-light py-5 height100vh">
  <div class="container">
    <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
	    <h2 class="font-weight-normal mb-4 mb-md-0">Submit Listings</h2>
	    <ul class="list-unstyled d-flex p-0 m-0">
				<li class="breadcrumb-item"><a href="/home">Home</a></li>
	      <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
	      <li class="breadcrumb-item active" aria-current="page">Submit Listings</li>
	    </ul>
    </nav>

    <form action="{{ route('courts.update', ['court'=>$court->id]) }}" method="POST">
      @method('PUT')
        @csrf

      <!-- About -->
      <div class="card">
        <div class="card-body px-6 pt-6 pb-1">
          <h3 class="h4 mb-4">About</h3>
          <p class="mb-5">We are not responsible for any damages caused by the use of this website, or by posting business listings here. Please use our site at your own discretion and exercise good judgement as well as common sense when advertising business here.</p>
            <div class="row">
              <div class="form-group col-md-6 mb-6">
                <label for="courtName">Court Name </label>
                <input type="text" class="form-control" id="courtName" name="name" placeholder="Court Name" value="{{ $court->name }}" required>
              </div>

              <div class="form-group col-md-6 mb-6">
                <label for="playgrounds_id">Playground Name</label>
                <div class="select-default bg-white">
                  <select class="select-location" name="playgrounds_id" required>

                    @foreach($playground as $play)
                     @if($playground->id === $court->playgrounds->id) 
                      <option selected value="{{ $playground->id }}">{{ $playground->name }}</option>
                       @else
                      <option value="{{ $play->id }}">{{ $play->name }}</option> 
                      @endif
                    @endforeach
                  </select>
                </div>
              </div>
              
              <div class="form-group col-md-12 mb-6">
                <label for="description">Description</label>
                <textarea class="form-control" rows="6" id="description" name="description" placeholder="Description" required>{{ $court->description }}</textarea>
              </div>

              <div class="form-group col-md-12 mb-6">
                <label for="court_statuses_id">Court Status</label>
                <div class="select-default bg-white">
                  <select class="select-location" name="court_statuses_id" required>

                      @foreach($court_statuses as $court_status)
                    <option value="{{ $court_status->id }}">{{ $court_status->name }}</option>
                      @endforeach
                  </select>
                </div>
              </div>

            </div>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-7 col-lg-6 col-xl-5">
          <div class="mb-6">
            <button type="submit" id="contact-submit" class="btn btn-lg btn-primary btn-block">submit</button>
          </div>
        </div>
      </div>

      @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
              @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
          </ul>
        </div>
      @endif

    </form>

  </div>
</section>

</div> <!-- element wrapper ends -->

@endsection

resources/views/courts/index.blade.php
@extends('layouts.page')

@section('caption', 'Courts')

@section('content')
<!-- ====================================
———	LISTING HALF MAP LIST
===================================== -->
<section class="main-contentiner map-half-content grid-two-items">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6 order-lg-2 pl-lg-0">
        <div class="inner-container">
          <div class="map-lg-fixed">
            <div class="map-container">
              <div id="listing-main-map" class="map-half"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 px-xl-6">
    
        <!-- List items goes here -->
            @foreach($courts as $court)
        <div class="card card-list card-listing" data-lat="-33.922125" data-lag="151.159277" data-id="1">
          <div class="row">
            <div class="col-sm-5 col-xl-4">
              <div class="card-list-img">
                <img class="listing-img" src="/assets/img/listing/listing-4.jpg" alt="things-4">
              </div>

            </div>
            <div class="col-sm-7 col-xl-8">
              <div class="card-body p-0">
                
                <div class="d-flex justify-content-between align-items-center mb-1">
                  <h3 class="card-title listing-title mb-0">
                    <a href="/courts/{{ $court->id }}"> {{ $court->name }} </a>
                  </h3>
                </div>

              </div>
                <a href="/playgrounds/{{ $court->playgrounds_id }}"> {{ $court->playgrounds->name }} </a>
                <p></p>
                <p class="mb-4"> {{ $court->description }} </p>
              <div>
                <button class="btn-like" data-toggle="tooltip" data-placement="top" title="Court Status">
                  <i class="text-primary" aria-hidden="true">{{ $court->court_statuses->name }}</i>
                </button>
              </div>
            </div>
          </div>
        </div>
            @endforeach

        {{ $courts->links() }}

</div> <!-- element wrapper ends -->

@endsection

resources/views/courts/view.blade.php
@extends('layouts.page')

@section('caption', 'Court')

@section('content')

<!-- ====================================
———	LISTING SINGLE HEADING
===================================== -->
<section class="py-7 pt-md-9 pb-md-8">
  <div class="container">
    <div class="d-md-flex flex-column flex-md-row justify-content-md-between align-items-end">
      <div class="mb-2 mb-md-0">
        <h1 class="single-listing-title"> {{ $court->name }}</h1>
        <p>Court Name</p>
      </div>
    </div>
  </div>
</section>

<!-- ====================================
———	LISTING DETAILS CAROUSEL
===================================== -->
<section>
  <div class="owl-carousel owl-theme listing-details-carousel nav-light-dark">

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-01.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-01.jpg" alt="Image" />
      </a>
    </div>

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-02.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-02.jpg" alt="Image" />
      </a>
    </div>

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-03.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-03.jpg" alt="Image" />
      </a>
    </div>

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-04.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-04.jpg" alt="Image" />
      </a>
    </div>

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-05.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-05.jpg" alt="Image" />
      </a>
    </div>

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-06.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-06.jpg" alt="Image" />
      </a>
    </div>

    <div class="single-item">
      <a class="overlay-dark" href="/assets/img/single-listing/store/store-img-big-07.jpg" data-fancybox="gallery"
        data-caption="Caption for single image">
        <img src="/assets/img/single-listing/store/store-img-07.jpg" alt="Image" />
      </a>
    </div>

  </div>
</section>

<!-- ====================================
———	MAIN CONTENT
===================================== -->
<section class="pt-7 pb-4 pt-md-9 pb-md-8">
  <div class="container">
    <div class="row">
      <div class="col-md-7 col-lg-8">

        <!-- Listing Main Content -->
        <div class="single-listing-content mb-6">

          <a href="/playgrounds/{{ $court->playgrounds_id }}"><h3 class="font-weight-normal">{{ $court->playgrounds->name }}</h3></a>
          <p>Playground name</p>

          <h3 class="font-weight-normal">Description</h3>
          <p class="mb-6">{{ $court->description }}</p> 

          <!-- Departments at this Store -->
          <div class="mb-6">
            <h4 class="font-weight-normal mb-4">Court Status</h4>
            <p class="mb-1">{{ $court->court_statuses->name }}</p>
          </div>

        </div>

        <hr> 

      </div>

      <!--======= Sidebar =======-->
      <div class="col-md-5 col-lg-4 pl-xl-8">

        <!-- Single listing Map -->
        <div class="map-sidebar border rounded mb-5">
          <div id="single-listing-map" data-lat="40.705793" data-lag="-74.006207"></div>
          <div class="px-6 py-5">
            <ul class="list-unstyled mb-0">
              <li class="d-flex align-items-start">
                <i class="fa fa-map-marker mr-3 mt-1" aria-hidden="true"></i>
                <span>2880 Broadway, New York, NY 10025, USA</span>
              </li>
            </ul>
          </div>
        </div>

      </div>

    </div>
  </div>
</section>

  </div> <!-- element wrapper ends -->

@endsection